id: I4480A44A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:03:03+00:00'
last_modified: '2022-06-08T13:02:27.946818+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1EE38
  title: རྗེ་བཙུན་མི་ལ་རས་པའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3A03:
      image_group_id: I1KG16862
      title: Volume 1 of rje btsun mi la ras pa'i rnam thar
      total_pages: 454
      order: 1
      base_file: 3A03.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
