id: P006964
initial_creation_type: ocr
source_metadata:
  id: bdr:W1EE38
  title: རྗེ་བཙུན་མི་ལ་རས་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    7355bb1467fd4fb0aa230d863a0197f0:
      image_group_id: I1KG16862
      title: ''
      volume_number: 1
      total_pages: 454
ebook_metadata:
  title: རྗེ་བཙུན་མི་ལ་རས་པའི་རྣམ་ཐར།
  author: ''
  sku: P006964
  cover: cover.jpg
  layers:
  - pagination
