id: P006964
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:33:15.054758
source_metadata:
  id: bdr:W1EE38
  title: རྗེ་བཙུན་མི་ལ་རས་པའི་རྣམ་ཐར།
  author: ''
  volumes:
    92ca72378a8f41b4a5511c7646ca40b3:
      image_group_id: I1KG16862
      title: Volume 1 of rje btsun mi la ras pa'i rnam thar
      volume_number: 1
      total_pages: 454
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
